'use client';
/** FR-REG-001 / WP-095. All views share one canonical selection and fixture session store. */
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import * as Dialog from '@radix-ui/react-dialog';
import { WorkbenchIcon } from '../WorkbenchIcon';
import { candidate, canonicalWindow, compatiblePass, filterChanges, mappedRevision, observedVerdict, revisionLabel, sameScope,
  type Integration, type Investigation, type Run, type Snapshot, type SourceHealth, type Verdict } from '../../lib/regression/model';
import { FIXTURE_STORAGE_KEY, FixtureSessions, fixtureSource, manifest, unconfiguredSource, type RegressionDataSource } from '../../lib/regression/source';
import { regressionQuery, regressionUrl, type RegressionQuery, type RegressionView } from '../../lib/regression/query';
import { RegressionTimeline } from './RegressionTimeline';
import { ExistingBisectSession } from './ExistingBisectSession';

const symbols={PASS:'✓',FAIL:'×',INCONCLUSIVE:'Ⅱ',SKIP:'↷',UNTESTED:'○'};
function Badge({verdict}:{verdict:keyof typeof symbols}): ReactNode {return <span className={`rg-badge rg-verdict-${verdict.toLowerCase()}`}>{symbols[verdict]} {verdict==='UNTESTED'?'Untested':verdict==='INCONCLUSIVE'?'Inconclusive':verdict}</span>;}
function download(name:string,value:unknown):void {const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type Modal={kind:'integration';point:Integration}|{kind:'evidence'}|{kind:'start'}|{kind:'verdict';verdict:'SKIP'|'INCONCLUSIVE'}|{kind:'request'}|{kind:'history'}|{kind:'queue'}|null;

export function RegressionWorkbench({fixtureEnabled=false,source:providedSource}: {fixtureEnabled?:boolean;source?:RegressionDataSource}):ReactNode {
  const router=useRouter(),params=useSearchParams();
  const source=providedSource??(fixtureEnabled?fixtureSource:unconfiguredSource);
  const [data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[reload,setReload]=useState(0);
  const [store,setStore]=useState<FixtureSessions|null>(null),[loadedSession,setSession]=useState<Investigation|null>(null),[storageError,setStorageError]=useState('');
  const [health,setHealth]=useState<SourceHealth>('ready'),[scenario,setScenario]=useState('ready');
  const [status,setStatus]=useState('attention'),[area,setArea]=useState('all'),[search,setSearch]=useState(''),[order,setOrder]=useState<'desc'|'asc'>('desc'),[page,setPage]=useState(1);
  const [zoom,setZoom]=useState(1),[full,setFull]=useState(false),[modal,setModal]=useState<Modal>(null),[reason,setReason]=useState(''),[message,setMessage]=useState('');
  const [mutating,setMutating]=useState(false),[writeLockSupported,setWriteLockSupported]=useState(false);
  const trigger=useRef<HTMLElement|SVGElement|null>(null);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setLoadError('');setData(null);
    void source.load(controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch((e:unknown)=>{if(!controller.signal.aborted)setLoadError(e instanceof Error?e.message:'Unable to load evidence.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();},[source,reload]);
  useEffect(()=>{if(source.kind!=='fixture')return;setWriteLockSupported(Boolean(navigator.locks));try{setStore(new FixtureSessions(window.localStorage));}catch{setStorageError('Browser storage is unavailable. Demo observations are read-only.');}},[source]);
  const fallback=useMemo(()=>({scope:data?.scope??{repository:'',branch:'',epoch:1},date:data?.runs.map(r=>r.date).sort().at(-1)??'',
    run:data?.runs.filter(r=>r.status==='FAIL'&&mappedRevision(data,r)).sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]?.id??''}),[data]);
  const query=regressionQuery(params,fallback);
  const scoped=Boolean(data&&sameScope(query.scope,data.scope));
  const runs=data&&scoped?data.runs.filter(r=>sameScope(r.scope,query.scope)&&r.date===query.date&&(query.type==='all'||r.type===query.type)
    &&(status==='all'||status==='attention'&&r.status!=='PASS'||r.status===status)).sort((a,b)=>b.completedAt.localeCompare(a.completedAt)):[];
  const run=runs.find(r=>r.id===query.run)??runs.find(r=>r.id===fallback.run)??runs[0]??null;
  const session=loadedSession&&run&&loadedSession.runId===run.id&&sameScope(loadedSession.scope,run.scope)?loadedSession:null;
  const selectedKey=JSON.stringify([query.scope,run?.id]);
  const currentSelection=useRef(selectedKey);currentSelection.current=selectedKey;
  useEffect(()=>{setSession(null);setStorageError('');setPage(1);setSearch('');setArea('all');setZoom(1);setModal(null);
    if(!store||!run)return;
    const load=()=>{try{setSession(store.get(run.scope,run.id));setStorageError('');}catch(e){setStorageError(e instanceof Error?e.message:'Cannot read saved demo sessions.');}};
    load();const sync=(e:StorageEvent)=>{if(e.key===FIXTURE_STORAGE_KEY||e.key===null)load();};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);
  // Run identity, rather than view/search/page, controls session restoration.
  },[store,selectedKey]); // eslint does not enable exhaustive-deps; selectedKey deliberately captures scope + run.
  const navigate=(patch:Partial<RegressionQuery>)=>router.replace(regressionUrl({...query,...patch}),{scroll:false});
  const selectRun=(r:Run)=>{setStatus(r.status==='PASS'?'all':'attention');navigate({run:r.id,date:r.date,type:'all',scope:r.scope});};
  const open=(value:Modal)=>{trigger.current=document.activeElement instanceof HTMLElement||document.activeElement instanceof SVGElement?document.activeElement:null;setReason('');setModal(value);};
  const act=(action:()=>void)=>{const selected=currentSelection.current;setMessage('');setMutating(true);
    // Web Locks serialize read/compare/write across tabs; a version check alone is not atomic in localStorage.
    const task=navigator.locks?navigator.locks.request(FIXTURE_STORAGE_KEY,()=>{if(currentSelection.current!==selected)throw new Error('The selection changed. No observation was written.');action();}):Promise.reject(new Error('This browser cannot lock local sessions. Demo recording is read-only.'));
    void task.catch((e:unknown)=>setMessage(e instanceof Error?e.message:'Unable to update the investigation.')).finally(()=>setMutating(false));};
  const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);setMessage('Copied to clipboard.');}catch{setMessage('Clipboard unavailable. Select and copy the full value shown in the inspector.');}};
  const pass=data&&run?compatiblePass(data,run):null;
  const endpoint=data&&run?mappedRevision(data,run):null;
  const good=session?.good??pass?.seq??null,bad=session?.bad??run?.seq??null;
  const points=data&&good!==null&&bad!==null?canonicalWindow(data,query.scope,good,bad):[];
  const preview=data&&run&&run.status==='FAIL'&&pass?{id:'preview',runId:run.id,scope:run.scope,good:pass.seq??0,bad:run.seq??0,originalGood:pass.seq??0,originalBad:run.seq??0,version:0,skipped:[],waiting:null,history:[]}:null;
  const calculation=data&&(session??preview)?candidate(data,session??preview!):null;
  const next=calculation?.next??null;
  const readonly=health!=='ready'||!store||Boolean(storageError)||source.kind!=='fixture'||mutating||!writeLockSupported;
  const localRecords=useMemo(()=>{try{return {history:store&&run?store.archive(run.scope,run.id):[],requests:store?.requests()??[],error:''};}catch(e){return {history:[],requests:[],error:e instanceof Error?e.message:'Unable to read local history.'};}},[store,selectedKey,session,modal]);
  const shown=filterChanges(points,search,area,order),pages=Math.max(1,Math.ceil(shown.length/8)),currentPage=Math.min(page,pages);
  const visible=shown.slice((currentPage-1)*8,currentPage*8);
  const baselinePoint=data?.integrations.find(p=>p.seq===good);
  const badPoint=data?.integrations.find(p=>p.seq===bad);
  const chartPoints=data&&pass?.seq!==null&&pass&&run?.seq!==null&&run?data.integrations.filter(p=>full||p.seq>=pass.seq!&&p.seq<=run.seq!):[];
  const setSourceState=(value:string)=>{setScenario(value);setHealth(value==='stale'||value==='offline'||value==='epoch_stale'?value:value==='ready'?'ready':'offline');};
  const mark=(verdict:Verdict,note='')=>{if(!data||!session||!store||readonly)return;act(()=>{setSession(store.mark(data,session,verdict,note,health));setModal(null);setPage(1);});};
  function runCards():ReactNode{return <div className="rg-run-cards">{runs.map(r=><button key={r.id} className={`rg-run-card ${run?.id===r.id?'is-selected':''}`} aria-pressed={run?.id===r.id} onClick={()=>selectRun(r)}><Badge verdict={r.status}/><strong>{r.title}</strong><span className="rg-mono">{r.id}</span><small>{r.type} · {r.completedAt.slice(11,16)} KST</small></button>)}</div>;}
  function evidence():ReactNode{return run?<section className="rg-panel rg-evidence"><div className="rg-between"><span className="rg-eyebrow">Selected evidence</span><Badge verdict={run.status}/></div><h2>{run.title}</h2><p className="rg-mono rg-muted">{run.id}</p><dl><dt>Tested build</dt><dd>{endpoint?revisionLabel(endpoint):'Unmapped revision'}</dd><dt>Completed · KST</dt><dd>{run.date} {run.completedAt.slice(11,16)}</dd><dt>Test type</dt><dd>MDVP / {run.type}</dd><dt>Environment</dt><dd>{run.context.environment}</dd></dl>{run.type==='MTBF'?<p className="rg-notice">{run.deviceHours} device-hours · {run.failures} failures. Source verdict only; no inferred confidence.</p>:null}<button className="rg-button rg-block" onClick={()=>open({kind:'evidence'})}>View test evidence <WorkbenchIcon name="chevron"/></button></section>:null;}
  function bisect():ReactNode{return <section className="rg-panel rg-bisect" aria-label="Regression bisect"><div className="rg-panel-heading"><h2><WorkbenchIcon name="range"/>{session?'Bisect session':'Bisect preview'}</h2><span className="rg-tag">LOCAL DEMO</span></div><div className="rg-panel-body">
    {!preview?<p className="rg-muted">A mapped FAIL and a compatible PASS are required. Inconclusive evidence cannot establish a FAIL boundary.</p>:<>
      <span className="rg-eyebrow">{session?'Next test candidate':'Canonical midpoint'}</span><div className="rg-candidate" data-testid="regression-next">{next?revisionLabel(next):calculation?.state==='boundary'?'First FAIL boundary candidate':'Unresolved range'}</div>
      <p className="rg-mono rg-muted">{next?`S-${next.seq} · ${next.sha.slice(0,12)}`:calculation?.state==='boundary'?'Reproduction confirmation required':'No available test candidate; skipped changes remain suspects.'}</p>
      <div className="rg-bisect-stats" aria-live="polite"><span><strong>{points.length}</strong> suspects</span><span><strong>{calculation?.testable??0}</strong> testable</span><span><strong>~{Math.ceil(Math.log2(Math.max(1,points.length)))}</strong> ideal checks</span></div>
      <p className="rg-small rg-muted">Ideal checks exclude skips and test duration.</p>
      {session?<><div className="rg-verdict-actions"><button className="rg-button rg-pass" disabled={readonly||!next} onClick={()=>mark('PASS')}>✓ PASS</button><button className="rg-button rg-fail" disabled={readonly||!next} onClick={()=>mark('FAIL')}>× FAIL</button><button className="rg-button" disabled={readonly||!next} onClick={()=>open({kind:'verdict',verdict:'INCONCLUSIVE'})}>Ⅱ Inconclusive</button><button className="rg-button" disabled={readonly||!next} onClick={()=>open({kind:'verdict',verdict:'SKIP'})}>↷ Skip</button></div>
        {calculation?.state==='awaiting_evidence'?<p className="rg-notice">Awaiting evidence. The candidate and both boundaries are unchanged. Retest, or explicitly skip with a reason.</p>:null}
        <button className="rg-button rg-block" disabled={readonly||!next} onClick={()=>open({kind:'request'})}>Review local test request</button>
        <div className="rg-between rg-session-foot"><button className="rg-text-button" onClick={()=>open({kind:'history'})}>Observation history ({session.history.length})</button><button className="rg-text-button" disabled={readonly} onClick={()=>act(()=>{store?.close(session);setSession(null);setMessage('Session archived. Its observations are preserved.');})}>Archive session</button></div>
      </>:<button className="rg-button rg-primary rg-block" disabled={readonly} onClick={()=>open({kind:'start'})}>Start bisect <WorkbenchIcon name="arrow"/></button>}
    </>}
    <p className="rg-small rg-muted">Fixture verdicts never call the production bisect API.</p><div className="rg-between"><button className="rg-text-button" onClick={()=>open({kind:'history'})}>View preserved sessions</button><button className="rg-text-button" onClick={()=>act(()=>{if(store&&run)setSession(store.get(run.scope,run.id));})}>Reload session</button></div>
  </div></section>;}
  function changesTable():ReactNode{return <section aria-label="Changes in suspect window"><div className="rg-section-heading"><div><h2>Changes in suspect window <span className="rg-count">{points.length}</span></h2><p>Integrations to investigate, not confirmed causes.</p></div><button className="rg-button" onClick={()=>{setOrder(order==='desc'?'asc':'desc');setPage(1);}}>{order==='desc'?'Newest first':'Integration order'} ↕</button></div>
    <div className="rg-table-tools"><div className="rg-chips" aria-label="Display filters">{['all','L1','PHY','RRC','RF','direct','missing'].map(a=><button key={a} aria-pressed={area===a} onClick={()=>{setArea(a);setPage(1);}}>{a==='all'?'All changes':a==='direct'?'Direct push':a==='missing'?'No binary':a}</button>)}</div><label className="rg-search"><WorkbenchIcon name="search"/><input aria-label="Search changes" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="PR / M / S / SHA / manifest"/></label></div>
    {(area!=='all'||search)?<p className="rg-filter-note">Display filter only. The canonical interval and midpoint are unchanged.</p>:null}
    <div className="rg-table-scroll" tabIndex={0} aria-label="Scrollable change table"><table><thead><tr><th>M / sequence</th><th>PR / change</th><th>Area</th><th>Integrated · KST</th><th>Binary</th><th>Selected test</th></tr></thead><tbody>{visible.map(p=><tr key={p.seq} className={p.seq===next?.seq?'is-next':p.pr===null?'is-direct':''}><td className="rg-mono"><button className="rg-row-open" onClick={()=>open({kind:'integration',point:p})}>{revisionLabel(p)}</button><small>S-{p.seq}</small></td><td><button className="rg-row-title" onClick={()=>open({kind:'integration',point:p})}><span>{p.pr===null?'◇ Direct push':`#${p.pr}`}</span>{p.title}</button><small className="rg-mono">{p.sha.slice(0,12)} · {p.author}</small></td><td><span className="rg-tag">{p.area}</span></td><td>{p.integratedAt.slice(5,16).replace('T',' ')}</td><td><span className={p.artifact?'rg-muted':'rg-warning'}>{p.artifact?'◇ Available':'◌ Not stored'}</span></td><td><Badge verdict={run?observedVerdict(p,run,pass,session):'UNTESTED'}/></td></tr>)}</tbody></table>{visible.length===0?<div className="rg-empty"><h3>No matching changes</h3><p>Clear the display filters to see the full suspect interval.</p><button className="rg-button" onClick={()=>{setSearch('');setArea('all');}}>Clear filters</button></div>:null}</div>
    <div className="rg-table-footer"><span>{shown.length} displayed / {points.length} canonical changes</span><div><button className="rg-button" aria-label="Previous changes page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>←</button><span>{currentPage} / {pages}</span><button className="rg-button" aria-label="Next changes page" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>→</button></div></div></section>;}
  const errorState=loadError||scenario==='error'||scenario==='permission';
  return <div className="regression-workbench" data-testid="regression-workbench">
    <div className="rg-fixture-banner" role="note"><WorkbenchIcon name="shield"/><strong>{source.kind==='fixture'?'SYNTHETIC FIXTURE':'MDVP NOT CONNECTED'}</strong><span>{source.kind==='fixture'?'Local investigation demo. No real MDVP, build, or equipment execution.':'Configure an approved data adapter to investigate real test results.'}</span></div>
    <header className="rg-heading"><div><p className="rg-eyebrow">Regression / Integration intelligence</p><h1>{query.view==='atlas'?'Revision Atlas':query.view==='inbox'?'Failure Inbox':'Daily Pulse'}</h1><p>Read the integration order. Follow the test evidence.</p></div><div className="rg-heading-actions"><div className="rg-view-switch" aria-label="Regression views">{(['atlas','inbox','pulse'] as RegressionView[]).map(v=><button key={v} aria-pressed={query.view===v} onClick={()=>navigate({view:v})}>{v==='atlas'?'Atlas':v==='inbox'?'Inbox':'Pulse'}</button>)}</div><button className="rg-button" disabled={!data||!run} onClick={()=>download('regression-investigation.json',{data_classification:'SYNTHETIC_FIXTURE_ONLY',scope:query.scope,run,baseline:pass,session,changes:points.map(p=>manifest(query.scope,p))})}><WorkbenchIcon name="external"/>Export</button></div></header>
    {data?<div className="rg-scope-bar"><label>Repository<select value={query.scope.repository} onChange={e=>navigate({scope:{...query.scope,repository:e.target.value}})}><option>{data.scope.repository}</option>{query.scope.repository!==data.scope.repository?<option>{query.scope.repository}</option>:null}</select></label><label>Branch<select aria-label="Regression branch" value={query.scope.branch} onChange={e=>navigate({scope:{...query.scope,branch:e.target.value}})}>{Array.from(new Set([data.scope.branch,'release/26A',query.scope.branch])).map(b=><option key={b}>{b}</option>)}</select></label><label>Result date · KST<input aria-label="Result date" type="date" value={query.date} onChange={e=>navigate({date:e.target.value,run:''})}/></label><label>Test type<select value={query.type} onChange={e=>navigate({type:e.target.value,run:''})}>{['all','Regression','Field','MTBF'].map(t=><option key={t} value={t}>{t==='all'?'All test types':t}</option>)}</select></label><label>Verdict<select value={status} onChange={e=>setStatus(e.target.value)}>{['attention','all','FAIL','PASS','INCONCLUSIVE'].map(s=><option key={s} value={s}>{s==='attention'?'Needs investigation':s==='all'?'All results':s}</option>)}</select></label><span className="rg-tag">Epoch {query.scope.epoch}</span></div>:null}
    {source.kind==='fixture'?<div className="rg-source-status"><span><i className={health==='ready'?'rg-connection-dot':'rg-connection-dot is-warning'}/>Fixture snapshot · {data?.capturedAt.slice(0,16).replace('T',' ')} KST</span><label>Preview source state <select aria-label="Preview source state" value={scenario} onChange={e=>setSourceState(e.target.value)}>{['ready','stale','offline','epoch_stale','permission','error','loading'].map(v=><option key={v}>{v}</option>)}</select></label><button className="rg-text-button" onClick={()=>open({kind:'queue'})}>Local request queue</button></div>:null}
    {health!=='ready'&&scenario!=='permission'&&scenario!=='error'&&scenario!=='loading'?<div className="rg-notice" role="alert">{health==='epoch_stale'?'History epoch changed. Existing judgments are locked.':health==='offline'?'MDVP is offline. Cached fixture evidence is read-only.':'MDVP evidence is stale. Refresh the source before recording results.'}</div>:null}
    <div role="status" aria-live="polite" className="rg-message">{message||storageError||localRecords.error}</div>
    {source.kind==='fixture'&&store&&!writeLockSupported?<p className="rg-notice">This browser does not support safe cross-tab locking. Evidence is available, but local recording is read-only.</p>:null}
    {loading||scenario==='loading'?<section className="rg-empty" aria-busy="true"><div className="rg-skeleton"/><h2>Loading investigation evidence…</h2></section>:errorState?<section className="rg-empty"><WorkbenchIcon name="shield"/><h2>{scenario==='permission'?'Access to this evidence is unavailable':source.kind==='unconfigured'?'MDVP integration is not configured':'Unable to load evidence'}</h2><p>{scenario==='permission'?'Your current repository scope does not allow this view.':loadError||'The evidence source could not be reached.'}</p>{source.kind==='fixture'?<button className="rg-button" onClick={()=>{setSourceState('ready');setReload(n=>n+1);}}>Retry evidence</button>:null}<Link href="/ranges">Open existing range investigation</Link></section>:!scoped||!run?<section className="rg-empty"><WorkbenchIcon name="branch"/><h2>{scoped?'No test results for these filters':'No evidence in this sequence space'}</h2><p>{scoped?'Choose another result date or test type.':'Main-branch numbers are never substituted for another branch or epoch.'}</p><button className="rg-button" onClick={()=>{setStatus('attention');navigate({scope:fallback.scope,date:fallback.date,type:'all',run:fallback.run});}}>Return to sample investigation</button></section>:<>
      {query.view==='pulse'?<section className="rg-panel rg-pulse"><h2>MDVP test calendar</h2><p>Result completion date × test type · not an integration axis</p><div className="rg-matrix-scroll"><table><thead><tr><th>MDVP type</th>{Array.from(new Set(data?.runs.map(r=>r.date))).sort().map(d=><th key={d}>{d.slice(5)}</th>)}</tr></thead><tbody>{(['Regression','Field','MTBF'] as const).map(t=><tr key={t}><th>{t}</th>{Array.from(new Set(data?.runs.map(r=>r.date))).sort().map(d=>{const rs=data?.runs.filter(r=>r.type===t&&r.date===d)??[];return <td key={d}><button className="rg-matrix-cell" aria-label={`${d} ${t}, ${rs.length} results`} onClick={()=>{setStatus('all');navigate({date:d,type:t,run:''});}}>{rs.length?(['FAIL','INCONCLUSIVE','PASS'] as const).filter(v=>rs.some(r=>r.status===v)).map(v=><span key={v} className={`rg-verdict-${v.toLowerCase()}`}>{symbols[v]} {rs.filter(r=>r.status===v).length} {v}</span>):'—'}</button></td>;})}</tr>)}</tbody></table></div></section>:null}
      <div className={`rg-workspace ${query.view==='inbox'?'rg-with-inbox':''}`}>
        {query.view==='inbox'?<aside className="rg-inbox" aria-label="Failure inbox"><div className="rg-section-heading"><h2>MDVP results</h2><span className="rg-count">{runs.length}</span></div>{runCards()}</aside>:null}
        <div className="rg-investigation"><div className="rg-run-selector"><label>Investigating<select aria-label="Selected MDVP result" value={run.id} onChange={e=>{const r=data?.runs.find(x=>x.id===e.target.value);if(r)selectRun(r);}}>{runs.map(r=><option key={r.id} value={r.id}>{r.id} · {r.title} · {r.status}</option>)}</select></label><span className="rg-mono rg-muted">{query.scope.branch} / E{query.scope.epoch}</span></div>
          {!endpoint?<div className="rg-notice"><h2>Map this binary to a revision first</h2><p>This run has no verified integration mapping. Dates and PR numbers cannot stand in for a full SHA. Range creation and bisect are disabled.</p><button className="rg-button" onClick={()=>open({kind:'evidence'})}>Inspect unmapped evidence</button></div>:!pass?<div className="rg-notice"><h2>No comparable previous PASS</h2><p>Another testcase, configuration, or environment cannot establish this baseline.</p></div>:null}
          {run.status==='INCONCLUSIVE'?<div className="rg-notice"><h2>More evidence is required</h2><p>MTBF source verdict: INCONCLUSIVE. {run.deviceHours} device-hours and {run.failures} failures do not authorize an automatic PASS/FAIL decision.</p></div>:null}
          {data&&endpoint&&pass&&good!==null&&bad!==null?<><section className="rg-panel"><div className="rg-panel-heading"><div><h2><WorkbenchIcon name="branch"/>Integration map</h2><p>First-parent changes with discrete MDVP evidence</p></div><div className="rg-map-controls"><button className="rg-button" onClick={()=>setFull(!full)}>{full?'Focus interval':'Full history'}</button><button className="rg-button" aria-label="Zoom out timeline" disabled={zoom===1} onClick={()=>setZoom(z=>z-1)}>−</button><span>{zoom}×</span><button className="rg-button" aria-label="Zoom in timeline" disabled={zoom===4} onClick={()=>setZoom(z=>z+1)}>+</button></div></div>
            <RegressionTimeline data={data} run={run} pass={pass} session={session} points={chartPoints} next={next} zoom={zoom} onPoint={p=>open({kind:'integration',point:p})} onRun={selectRun}/>
            <div className="rg-legend"><span>✓ PASS</span><span>× FAIL</span><span>Ⅱ Inconclusive</span><span>○ Untested</span><span>◇ Direct push</span><span>◌ No binary</span><strong>┊ Next candidate</strong></div><p className="rg-map-caption">Markers sit at the tested revision, not at the test completion time. Use arrow keys to move between points.</p></section>
            <div className="rg-focus-summary" data-testid="regression-bounds"><div><p className="rg-eyebrow">{session?'Active suspect interval':'Suggested interval · confirm before bisect'}</p><h2>{baselinePoint?revisionLabel(baselinePoint):good} <span>→</span> {badPoint?revisionLabel(badPoint):bad}</h2><p className="rg-mono">(S-{good}, S-{bad}] · PASS excluded, {run.status==='FAIL'?'FAIL':'selected revision'} included</p></div><div className="rg-summary-count"><strong>{points.length}</strong><span>{points.filter(p=>p.pr!==null).length} PR + {points.filter(p=>p.pr===null).length} direct push</span></div></div></>:null}
        </div><aside className="rg-side">{bisect()}{evidence()}<p className="rg-context-note"><WorkbenchIcon name="shield"/>Only a PASS from the same testcase, signature, hardware, environment, configuration and policy is comparable.</p></aside>
        <div className="rg-changes">{data&&endpoint&&pass&&good!==null&&bad!==null?changesTable():null}</div>
      </div>
    </>}
    <Dialog.Root open={modal!==null} onOpenChange={value=>{if(!value)setModal(null);}}><Dialog.Portal><Dialog.Overlay className="rg-overlay"/><Dialog.Content className={`rg-dialog ${modal?.kind==='integration'||modal?.kind==='evidence'||modal?.kind==='history'?'rg-sheet':''}`} onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus({preventScroll:true});}}>
      <Dialog.Title>{modal?.kind==='integration'?'Integration detail':modal?.kind==='evidence'?'MDVP test evidence':modal?.kind==='start'?'Confirm comparable baseline':modal?.kind==='verdict'?'Record an uncertain observation':modal?.kind==='request'?'Review local test request':modal?.kind==='queue'?'Local request queue':'Preserved observation history'}</Dialog.Title>
      <Dialog.Description>Synthetic fixture only. No external test or build is executed.</Dialog.Description><Dialog.Close className="rg-dialog-close" aria-label="Close inspector"><WorkbenchIcon name="close"/></Dialog.Close>
      {modal?.kind==='integration'?<><div className="rg-detail-title">{revisionLabel(modal.point)}</div><h3>{modal.point.title}</h3><dl className="rg-detail-list"><dt>Canonical revision</dt><dd>{query.scope.repository} / {query.scope.branch} / E{query.scope.epoch} / S-{modal.point.seq}</dd><dt>Full commit SHA</dt><dd className="rg-mono">{modal.point.sha}<button className="rg-button" onClick={()=>void copy(modal.point.sha)}>Copy SHA</button></dd><dt>Pull request</dt><dd>{modal.point.pr===null?'Direct push · no linked PR':`#${modal.point.pr}`}</dd><dt>Author / integrated</dt><dd>{modal.point.author} · {modal.point.integratedAt}</dd><dt>Changed file</dt><dd className="rg-mono">{modal.point.file} · +{modal.point.additions} / −{modal.point.deletions}</dd><dt>Build / binary</dt><dd>{modal.point.build} · {modal.point.artifact?'Available':'Not stored'}</dd><dt>Exact artifact digest</dt><dd className="rg-mono">{modal.point.artifact?modal.point.digest:'Unavailable — revision remains a suspect.'}</dd></dl><button className="rg-button rg-primary" onClick={()=>download(`S-${modal.point.seq}-manifest.json`,manifest(query.scope,modal.point))}>Download fixture manifest</button></>:null}
      {modal?.kind==='evidence'&&run?<><Badge verdict={run.status}/><h3>{run.title}</h3><dl className="rg-detail-list"><dt>Run / completed</dt><dd>{run.id} · {run.completedAt}</dd><dt>Revision mapping</dt><dd className="rg-mono">{endpoint?`${revisionLabel(endpoint)} / S-${endpoint.seq} / ${endpoint.sha}`:'Unmapped — investigation locked'}</dd>{Object.entries(run.context).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}<dt>Exposure / failures</dt><dd>{run.deviceHours} device-hours / {run.failures}</dd><dt>Comparable PASS</dt><dd>{pass?`${pass.id} · ${pass.completedAt}`:'None'}</dd></dl><p className="rg-notice">Source-provided verdict. No confidence interval or automatic MTBF qualification is inferred.</p></>:null}
      {modal?.kind==='start'&&run&&pass?<><div className="rg-confirm-endpoints"><Badge verdict="PASS"/><strong>{pass.id} · S-{pass.seq}</strong><Badge verdict="FAIL"/><strong>{run.id} · S-{run.seq}</strong></div><p>Same testcase, failure signature, hardware, environment, configuration and policy:</p><pre>{JSON.stringify(run.context,null,2)}</pre><button className="rg-button rg-primary" disabled={readonly} onClick={()=>act(()=>{if(data&&store){setSession(store.start(data,run,crypto.randomUUID()));setModal(null);}})}>Use this PASS and start</button></>:null}
      {modal?.kind==='verdict'?<><p>{modal.verdict==='SKIP'?'Keep this revision in the suspect interval, but choose another testable candidate.':'Preserve this candidate and both boundaries for another test.'}</p><label className="rg-form-label">Reason (required)<textarea aria-label="Observation reason" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label><button className="rg-button rg-primary" disabled={readonly||!reason.trim()} onClick={()=>mark(modal.verdict,reason)}>Record {modal.verdict.toLowerCase()}</button></>:null}
      {modal?.kind==='request'&&next&&run?<><p className="rg-notice">This adds a request to this browser only. It does not dispatch to MDVP.</p><pre>{JSON.stringify({revision:manifest(run.scope,next),test:run.context},null,2)}</pre><button className="rg-button rg-primary" disabled={readonly} onClick={()=>act(()=>{if(data&&session&&store){store.enqueue(data,session,run,health);setModal(null);setMessage('Added to local fixture queue. No external request was sent.');}})}>Add to local queue</button></>:null}
      {modal?.kind==='history'&&store&&run?<div className="rg-history">{[...(session?[session]:[]),...localRecords.history].map(s=><section key={s.id}><h3>{s.id===session?.id?'Current session':'Archived session'} · v{s.version}</h3><p className="rg-mono">{s.scope.repository} / {s.scope.branch} / E{s.scope.epoch}</p>{s.history.length?s.history.map((o,i)=><div className="rg-history-row" key={`${s.id}-${i}`}><span className="rg-mono">S-{o.seq}<small>{o.at}</small></span><Badge verdict={o.verdict}/><p>{o.reason||'Manual fixture verdict'}</p></div>):<p>No observations recorded.</p>}</section>)}{!session&&!localRecords.history.length?<p>No preserved observations yet.</p>:null}{localRecords.error?<p role="alert">{localRecords.error}</p>:null}</div>:null}
      {modal?.kind==='queue'&&store?<div className="rg-history">{localRecords.requests.length?localRecords.requests.map(r=><div className="rg-history-row" key={r.id}><strong>{r.runId} · S-{r.seq}</strong><span className="rg-tag">LOCAL ONLY</span><p className="rg-mono">{r.digest}</p></div>):<p>No local requests.</p>}{localRecords.error?<p role="alert">{localRecords.error}</p>:null}</div>:null}
    </Dialog.Content></Dialog.Portal></Dialog.Root>
    {source.kind==='unconfigured'?<ExistingBisectSession/>:null}
  </div>;
}
