'use client';

import { cloneElement, createContext, forwardRef, isValidElement, useContext, useEffect, useId, useRef, useState, type ComponentPropsWithoutRef as Props, type CSSProperties, type HTMLAttributes, type ReactElement, type ReactNode, type Ref } from 'react';
import * as RCheckbox from '@radix-ui/react-checkbox';
import * as RCollapsible from '@radix-ui/react-collapsible';
import * as RDialog from '@radix-ui/react-dialog';
import * as RDropdown from '@radix-ui/react-dropdown-menu';
import * as RSelect from '@radix-ui/react-select';
import * as RSwitch from '@radix-ui/react-switch';
import * as RTabs from '@radix-ui/react-tabs';
import { Check, ChevronDown, Copy, LoaderCircle, X } from 'lucide-react';

type Tone = 'neutral' | 'accent' | 'success' | 'warning' | 'danger' | 'info';
type Size = 'sm' | 'md' | 'lg';
export type Status = 'queued' | 'running' | 'waiting' | 'success' | 'partial' | 'danger' | 'neutralEnd';
function cx(...values: Array<string | false | null | undefined>): string { return values.filter(Boolean).join(' '); }

interface ButtonProps extends Props<'button'> { variant?: 'primary' | 'secondary' | 'ghost'; tone?: Tone; size?: Size; loading?: boolean; blockedReason?: string; iconStart?: ReactNode; iconEnd?: ReactNode; }
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ variant = 'primary', tone = 'neutral', size = 'md', loading = false, blockedReason, iconStart, iconEnd, className, children, disabled, type = 'button', ...props }, ref) {
  return <button ref={ref} {...props} type={type} disabled={disabled || loading || Boolean(blockedReason)} aria-busy={loading || undefined} title={blockedReason ?? props.title} className={cx('ui-button', `ui-button--${variant}`, `ui-button--${tone}`, `ui-button--${size}`, className)}>{loading ? <LoaderCircle className="ui-spin" size={15} aria-hidden="true" /> : iconStart}{children}{iconEnd}</button>;
});
export const IconButton = forwardRef<HTMLButtonElement, Omit<ButtonProps, 'children'> & { icon: ReactNode; 'aria-label': string }>(function IconButton({ icon, className, ...props }, ref) { return <Button ref={ref} {...props} className={cx('ui-icon-button', className)}>{icon}</Button>; });

interface SurfaceProps extends HTMLAttributes<HTMLElement> { as?: 'div' | 'section' | 'aside'; size?: Size; }
export const Panel = forwardRef<HTMLElement, SurfaceProps>(function Panel({ as: Tag = 'div', size, className, ...props }, ref) { return <Tag ref={ref as Ref<HTMLDivElement>} {...props} className={cx('ui-panel', size && `ui-panel--${size}`, className)} />; });
export const Card = forwardRef<HTMLElement, Omit<SurfaceProps, 'as'> & { as?: 'div' | 'button' | 'a'; href?: string }>(function Card({ as: Tag = 'div', size, className, ...props }, ref) { return <Tag ref={ref as Ref<HTMLDivElement & HTMLButtonElement & HTMLAnchorElement>} {...props} className={cx('ui-card', size && `ui-card--${size}`, className)} />; });
export const CardGrid = forwardRef<HTMLDivElement, Props<'div'>>(function CardGrid({ className, ...props }, ref) { return <div ref={ref} {...props} className={cx('ui-card-grid', className)} />; });
export const Badge = forwardRef<HTMLSpanElement, Props<'span'> & { tone?: Tone; icon?: ReactNode }>(function Badge({ tone = 'neutral', icon, className, children, ...props }, ref) { return <span ref={ref} {...props} className={cx('ui-badge', `ui-badge--${tone}`, className)}>{icon}{children}</span>; });
export const StatusBadge = forwardRef<HTMLSpanElement, Props<'span'> & { status: Status; icon?: ReactNode; label?: string }>(function StatusBadge({ status, icon, label, className, ...props }, ref) { return <span ref={ref} {...props} className={cx('ui-status-badge', `ui-status-badge--${status}`, className)}>{icon}<span>{label ?? status}</span></span>; });

const TableHead = forwardRef<HTMLTableSectionElement, Props<'thead'>>(function Head({ className, ...props }, ref) { return <thead ref={ref} {...props} className={cx('ui-table-head', className)} />; });
const TableBody = forwardRef<HTMLTableSectionElement, Props<'tbody'>>(function Body({ className, ...props }, ref) { return <tbody ref={ref} {...props} className={cx('ui-table-body', className)} />; });
const TableRow = forwardRef<HTMLTableRowElement, Props<'tr'>>(function Row({ className, ...props }, ref) { return <tr ref={ref} {...props} className={cx('ui-table-row', className)} />; });
const TableHeaderCell = forwardRef<HTMLTableCellElement, Props<'th'>>(function HeaderCell({ className, ...props }, ref) { return <th ref={ref} {...props} className={cx('ui-table-header-cell', className)} />; });
const TableCell = forwardRef<HTMLTableCellElement, Props<'td'> & { numeric?: boolean }>(function Cell({ numeric, className, ...props }, ref) { return <td ref={ref} {...props} className={cx('ui-table-cell', numeric && 'ui-table-cell--numeric', className)} />; });
const TableRoot = forwardRef<HTMLDivElement, Props<'table'> & { caption?: ReactNode; scrollContainerProps?: Props<'div'> }>(function TableRoot({ caption, scrollContainerProps, children, className, ...props }, ref) { return <div ref={ref} {...scrollContainerProps} className={cx('ui-table-scroll', className, scrollContainerProps?.className)}><table {...props} className="ui-table">{caption ? <caption>{caption}</caption> : null}{children}</table></div>; });
export const Table = Object.assign(TableRoot, { Head: TableHead, Body: TableBody, Row: TableRow, HeaderCell: TableHeaderCell, Cell: TableCell });
export const CodeBlock = forwardRef<HTMLPreElement, Props<'pre'> & { code: string; language?: string }>(function CodeBlock({ code, language, className, ...props }, ref) { return <pre ref={ref} {...props} className={cx('ui-code-block', className)}><code data-language={language}>{code}</code></pre>; });
export const Kbd = forwardRef<HTMLElement, Props<'kbd'>>(function Kbd({ className, ...props }, ref) { return <kbd ref={ref} {...props} className={cx('ui-kbd', className)} />; });
const TimelineStep = forwardRef<HTMLLIElement, Omit<Props<'li'>, 'onSelect'> & { marker?: ReactNode; selected?: boolean; onSelect?: () => void }>(function TimelineStep({ marker, selected, onSelect, className, children, ...props }, ref) { return <li ref={ref} {...props} className={cx('ui-timeline-step', selected && 'is-selected', className)}>{onSelect ? <button type="button" onClick={onSelect} aria-pressed={selected}>{marker}{children}</button> : <div className="ui-timeline-content">{marker}{children}</div>}</li>; });
export const Timeline = Object.assign(forwardRef<HTMLOListElement, Props<'ol'>>(function Timeline({ className, ...props }, ref) { return <ol ref={ref} {...props} className={cx('ui-timeline', className)} />; }), { Step: TimelineStep });

interface FieldContextValue { id: string; hint: string | undefined; required: boolean | undefined; invalid: boolean; }
const FieldContext = createContext<FieldContextValue | undefined>(undefined);
function describedBy(...ids: Array<string | undefined>): string | undefined { return [...new Set(ids.filter(Boolean))].join(' ') || undefined; }
interface FieldProps extends Omit<Props<'div'>, 'children'> { label: string; description?: ReactNode; error?: ReactNode; required?: boolean; children: ReactElement; }
export const Field = forwardRef<HTMLDivElement, FieldProps>(function Field({ id, label, description, error, required, children, className, ...props }, ref) {
  const generated = useId();
  const native = isValidElement<Props<'input'>>(children) && typeof children.type === 'string';
  const childId = isValidElement<{ id?: string }>(children) ? children.props.id : undefined;
  const fieldId = childId ?? id ?? generated;
  const hint = error || description ? `${fieldId}-hint` : undefined;
  return <FieldContext.Provider value={{ id: fieldId, hint, required, invalid: Boolean(error) }}><div ref={ref} {...props} className={cx('ui-field', className)}><label htmlFor={fieldId}>{label}{required ? <span aria-hidden="true"> *</span> : null}</label>{native ? cloneElement(children, { id: fieldId, required: children.props.required ?? required, 'aria-invalid': children.props['aria-invalid'] ?? Boolean(error), 'aria-describedby': describedBy(children.props['aria-describedby'], hint) }) : children}{hint ? <p id={hint} className={error ? 'ui-field-error' : 'ui-field-description'}>{error ?? description}</p> : null}</div></FieldContext.Provider>;
});
export const TextField = forwardRef<HTMLInputElement, Omit<Props<'input'>, 'size'> & { iconStart?: ReactNode; invalid?: boolean; size?: Size; variant?: 'solid' | 'glass' }>(function TextField({ iconStart, invalid, className, size, variant, ...props }, ref) {
  const field = useContext(FieldContext);
  return <span className={cx('ui-input-wrap', (invalid ?? field?.invalid) && 'is-invalid', className)} data-size={size} data-variant={variant}>{iconStart}<input ref={ref} {...props} id={props.id ?? field?.id} required={props.required ?? field?.required ?? false} className="ui-input" aria-invalid={props['aria-invalid'] ?? invalid ?? field?.invalid} aria-describedby={describedBy(props['aria-describedby'], field?.hint)} /></span>;
});
export const TextArea = forwardRef<HTMLTextAreaElement, Props<'textarea'> & { invalid?: boolean; variant?: 'solid' | 'glass' }>(function TextArea({ invalid, className, variant, ...props }, ref) { const field = useContext(FieldContext); return <textarea ref={ref} {...props} id={props.id ?? field?.id} required={props.required ?? field?.required ?? false} data-variant={variant} className={cx('ui-textarea', (invalid ?? field?.invalid) && 'is-invalid', className)} aria-invalid={props['aria-invalid'] ?? invalid ?? field?.invalid} aria-describedby={describedBy(props['aria-describedby'], field?.hint)} />; });
function SelectRoot({ required, ...props }: Props<typeof RSelect.Root>) { const field = useContext(FieldContext); return <RSelect.Root {...props} required={required ?? field?.required ?? false} />; }
const SelectContent = forwardRef<HTMLDivElement, Props<typeof RSelect.Content>>(function SelectContent({ className, children, position = 'popper', ...props }, ref) { return <RSelect.Portal><RSelect.Content ref={ref} {...props} className={cx('ui-select-content', className)} position={position}><RSelect.Viewport>{children}</RSelect.Viewport></RSelect.Content></RSelect.Portal>; });
const SelectTrigger = forwardRef<HTMLButtonElement, Props<typeof RSelect.Trigger> & { size?: Size; invalid?: boolean }>(function SelectTrigger({ className, children, size, invalid, ...props }, ref) { const field = useContext(FieldContext); return <RSelect.Trigger ref={ref} {...props} id={props.id ?? field?.id} aria-required={props['aria-required'] ?? field?.required} aria-invalid={props['aria-invalid'] ?? invalid ?? field?.invalid} aria-describedby={describedBy(props['aria-describedby'], field?.hint)} data-size={size} className={cx('ui-select-trigger', className)}>{children}<RSelect.Icon><ChevronDown size={14} aria-hidden="true" /></RSelect.Icon></RSelect.Trigger>; });
const SelectItem = forwardRef<HTMLDivElement, Props<typeof RSelect.Item> & { indicator?: ReactNode }>(function SelectItem({ indicator = <Check size={13} />, className, children, ...props }, ref) { return <RSelect.Item ref={ref} {...props} className={cx('ui-select-item', className)}><RSelect.ItemText>{children}</RSelect.ItemText><RSelect.ItemIndicator>{indicator}</RSelect.ItemIndicator></RSelect.Item>; });
export const Select = { Root: SelectRoot, Trigger: SelectTrigger, Value: RSelect.Value, Content: SelectContent, Item: SelectItem, Group: RSelect.Group, Label: RSelect.Label };
export const Checkbox = forwardRef<HTMLButtonElement, Props<typeof RCheckbox.Root> & { indicator?: ReactNode }>(function Checkbox({ indicator = <Check size={13} />, className, children, ...props }, ref) { const field = useContext(FieldContext); return <RCheckbox.Root ref={ref} {...props} id={props.id ?? field?.id} required={props.required ?? field?.required ?? false} aria-invalid={props['aria-invalid'] ?? field?.invalid} aria-describedby={describedBy(props['aria-describedby'], field?.hint)} className={cx('ui-checkbox', className)}>{children}<RCheckbox.Indicator>{indicator}</RCheckbox.Indicator></RCheckbox.Root>; });
export const Switch = forwardRef<HTMLButtonElement, Props<typeof RSwitch.Root>>(function Switch({ className, ...props }, ref) { const field = useContext(FieldContext); return <RSwitch.Root ref={ref} {...props} id={props.id ?? field?.id} required={props.required ?? field?.required ?? false} aria-invalid={props['aria-invalid'] ?? field?.invalid} aria-describedby={describedBy(props['aria-describedby'], field?.hint)} className={cx('ui-switch', className)}><RSwitch.Thumb /></RSwitch.Root>; });

const DialogContent = forwardRef<HTMLDivElement, Props<typeof RDialog.Content> & { size?: Size }>(function DialogContent({ className, size = 'md', children, onOpenAutoFocus, onCloseAutoFocus, ...props }, ref) {
  const invokingElement = useRef<HTMLElement | null>(null);
  return <RDialog.Portal><RDialog.Overlay className="ui-overlay" /><RDialog.Content ref={ref} {...props} onOpenAutoFocus={event => { invokingElement.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; onOpenAutoFocus?.(event); }} onCloseAutoFocus={event => { if (onCloseAutoFocus) { onCloseAutoFocus(event); return; } if (invokingElement.current?.isConnected) { event.preventDefault(); invokingElement.current.focus({ preventScroll: true }); } }} className={cx('ui-dialog', `ui-dialog--${size}`, className)}>{children}</RDialog.Content></RDialog.Portal>;
});
export const Dialog = { Root: RDialog.Root, Trigger: RDialog.Trigger, Content: DialogContent, Title: RDialog.Title, Description: RDialog.Description, Close: RDialog.Close };
const MenuContent = forwardRef<HTMLDivElement, Props<typeof RDropdown.Content>>(function MenuContent({ className, children, ...props }, ref) { return <RDropdown.Portal><RDropdown.Content ref={ref} {...props} className={cx('ui-menu-content', className)}>{children}</RDropdown.Content></RDropdown.Portal>; });
const MenuItem = forwardRef<HTMLDivElement, Props<typeof RDropdown.Item> & { tone?: Tone; icon?: ReactNode }>(function MenuItem({ tone, icon, className, children, ...props }, ref) { return <RDropdown.Item ref={ref} {...props} className={cx('ui-menu-item', tone === 'danger' && 'ui-menu-item--danger', className)}>{icon}{children}</RDropdown.Item>; });
export const DropdownMenu = { Root: RDropdown.Root, Trigger: RDropdown.Trigger, Content: MenuContent, Item: MenuItem, Label: RDropdown.Label, Separator: RDropdown.Separator };
const TabsContext = createContext<string | undefined>(undefined);
function TabsRoot({ value, defaultValue, onValueChange, children, ...props }: Props<typeof RTabs.Root>) { const [internal, setInternal] = useState(defaultValue); const current = value ?? internal; return <TabsContext.Provider value={current}><RTabs.Root {...props} value={current ?? ''} onValueChange={next => { setInternal(next); onValueChange?.(next); }}>{children}</RTabs.Root></TabsContext.Provider>; }
const TabsContent = forwardRef<HTMLDivElement, Props<typeof RTabs.Content>>(function TabsContent({ value, hidden, ...props }, ref) { const current = useContext(TabsContext); return <RTabs.Content ref={ref} {...props} value={value} hidden={hidden || current !== value} />; });
export const Tabs = { Root: TabsRoot, List: RTabs.List, Trigger: RTabs.Trigger, Content: TabsContent };
export const Collapsible = { Root: RCollapsible.Root, Trigger: RCollapsible.Trigger, Content: RCollapsible.Content };

export const Banner = forwardRef<HTMLDivElement, Omit<Props<'div'>, 'title'> & { tone?: Tone; title?: ReactNode; icon?: ReactNode; action?: ReactNode }>(function Banner({ tone = 'info', title, icon, action, className, children, ...props }, ref) { return <div ref={ref} role={tone === 'danger' ? 'alert' : 'status'} {...props} className={cx('ui-banner', `ui-banner--${tone}`, className)}>{icon}<div>{title ? <strong>{title}</strong> : null}<div>{children}</div></div>{action}</div>; });
export const EmptyState = forwardRef<HTMLDivElement, Omit<Props<'div'>, 'title'> & { title: ReactNode; description?: ReactNode; action?: ReactNode; icon?: ReactNode }>(function EmptyState({ title, description, action, icon, className, ...props }, ref) { return <div ref={ref} {...props} className={cx('ui-empty-state', className)}>{icon}{isValidElement(title) ? title : <h2>{title}</h2>}{description ? <p>{description}</p> : null}{action}</div>; });
export const Meter = forwardRef<HTMLDivElement, Props<'div'> & { value: number; min?: number; max?: number; valueText: string; 'aria-label': string }>(function Meter({ value, min = 0, max = 100, valueText, className, ...props }, ref) { const bounded = Math.max(min, Math.min(max, value)); const pct = max > min ? (bounded - min) / (max - min) * 100 : 0; return <div ref={ref} {...props} role="meter" aria-valuemin={min} aria-valuemax={max} aria-valuenow={bounded} aria-valuetext={valueText} className={cx('ui-meter', className)}><span style={{ width: `${pct}%` }} /></div>; });
export const Spinner = forwardRef<HTMLDivElement, Props<'div'> & { label: string; size?: Size }>(function Spinner({ label, className, size = 'md', ...props }, ref) { return <div ref={ref} {...props} role="status" className={cx('ui-spinner', className)}><LoaderCircle className="ui-spin" size={size === 'sm' ? 14 : 18} aria-hidden="true" /><span>{label}</span></div>; });
export const Skeleton = forwardRef<HTMLDivElement, Props<'div'> & { label: string }>(function Skeleton({ label, className, ...props }, ref) { return <div ref={ref} {...props} role={label ? 'status' : undefined} aria-label={label || undefined} className={cx('ui-skeleton', className)} />; });
export const FilterChip = forwardRef<HTMLSpanElement, Props<'span'> & { onRemove: () => void; removeLabel: string; disabled?: boolean }>(function FilterChip({ children, onRemove, removeLabel, disabled, className, ...props }, ref) { return <span ref={ref} {...props} className={cx('ui-filter-chip', className)}>{children}<button type="button" disabled={disabled} onClick={onRemove} aria-label={removeLabel}><X size={12} aria-hidden="true" /></button></span>; });
export const FilterToolbar = forwardRef<HTMLDivElement, Props<'div'>>(function FilterToolbar({ className, ...props }, ref) { return <div ref={ref} {...props} className={cx('ui-filter-toolbar', className)} />; });
export const Breadcrumb = forwardRef<HTMLElement, Props<'nav'>>(function Breadcrumb({ className, ...props }, ref) { return <nav ref={ref} {...props} aria-label={props['aria-label'] ?? 'Breadcrumb'} className={cx('ui-breadcrumb', className)} />; });
export const CopyButton = forwardRef<HTMLSpanElement, Props<'span'> & { value: string; label?: string }>(function CopyButton({ value, label = 'Copy', className, ...props }, ref) {
  const [message, setMessage] = useState(''); const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => { clearTimeout(timer.current); }, []);
  async function copy() { clearTimeout(timer.current); try { await navigator.clipboard.writeText(value); setMessage('Copied'); } catch { setMessage('Copy failed. Select and copy the identifier manually.'); } timer.current = setTimeout(() => { setMessage(''); }, 4000); }
  return <span ref={ref} {...props} className={className}><button type="button" className="ui-copy-button" onClick={() => { void copy(); }}><Copy size={13} aria-hidden="true" />{label}</button><span role="status" aria-live="polite" className="ui-copy-status">{message}</span></span>;
});
/** CR-111: the displayed identifier itself is the copy target (no separate Copy button/icon), styled as text. Same clipboard/status contract as `CopyButton`. */
export const CopyText = forwardRef<HTMLButtonElement, Omit<Props<'button'>, 'children'> & { value: string; copyLabel: string; children: ReactNode }>(function CopyText({ value, copyLabel, className, children, ...props }, ref) {
  const [message, setMessage] = useState(''); const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => { clearTimeout(timer.current); }, []);
  async function copy() { clearTimeout(timer.current); try { await navigator.clipboard.writeText(value); setMessage('Copied'); } catch { setMessage('Copy failed. Select and copy the identifier manually.'); } timer.current = setTimeout(() => { setMessage(''); }, 4000); }
  return <span className="ui-copy-text-wrap"><button ref={ref} type="button" {...props} aria-label={copyLabel} onClick={() => { void copy(); }} className={cx('ui-copy-text', className)}>{children}</button><span role="status" aria-live="polite" className="ui-copy-status">{message}</span></span>;
});

export const WorkbenchLayout = forwardRef<HTMLDivElement, Props<'div'> & { inspector?: ReactNode; width?: number; onWidthChange?: (width: number) => void }>(function WorkbenchLayout({ inspector, children, width = 38, onWidthChange, className, style, ...props }, ref) {
  const rangeId = useId(); const bounded = Math.max(25, Math.min(60, width));
  return <div ref={ref} {...props} data-inspecting={inspector ? '' : undefined} className={cx('ui-workbench', Boolean(inspector) && 'ui-workbench--inspect', className)} style={{ '--ui-inspector-width': `${bounded}%`, ...style } as CSSProperties}><div className="ui-workbench-results">{children}</div>{inspector ? <aside className="ui-workbench-inspector">{onWidthChange ? <div className="ui-workbench-resize"><label htmlFor={rangeId}>Preview width</label><input id={rangeId} type="range" min={25} max={60} value={bounded} onChange={event => { onWidthChange(Number(event.target.value)); }} aria-valuetext={`${bounded}%`} /></div> : null}{inspector}</aside> : null}</div>;
});
export const DetailInspector = forwardRef<HTMLElement, Props<'section'> & { label: string; onClose: () => void; returnFocusRef?: { readonly current: HTMLElement | null } }>(function DetailInspector({ label, onClose, returnFocusRef, children, className, onKeyDown, ...props }, ref) {
  function close() { const target = returnFocusRef?.current; onClose(); if (target?.isConnected) target.focus({ preventScroll: true }); }
  return <section ref={ref} {...props} aria-label={label} className={cx('ui-detail-inspector', className)} onKeyDown={event => { onKeyDown?.(event); if (!event.defaultPrevented && event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); close(); } }}><header><h2>{label}</h2><button type="button" onClick={close} className="ui-detail-close" aria-label="Close preview"><X size={15} aria-hidden="true" /></button></header>{children}</section>;
});

interface AppShellProps extends Props<'div'> { nav: ReactNode; topBar?: ReactNode; mainId?: string; skipLinkLabel?: string; navLabel?: string; navCloseLabel?: string; navOpen?: boolean; onNavOpenChange?: (open: boolean) => void; routeKey?: string; }
export const AppShell = forwardRef<HTMLDivElement, AppShellProps>(function AppShell({ nav, topBar, children, mainId = 'main-content', skipLinkLabel = 'Skip to content', navLabel = 'Main navigation', navCloseLabel = 'Close navigation', navOpen, onNavOpenChange, routeKey, className, ...props }, ref) {
  const [internalOpen, setInternalOpen] = useState(false); const main = useRef<HTMLElement>(null); const previousRoute = useRef(routeKey); const routeClosing = useRef(false); const open = navOpen ?? internalOpen; const changeRef = useRef(onNavOpenChange); changeRef.current = onNavOpenChange;
  function changeOpen(next: boolean) { setInternalOpen(next); onNavOpenChange?.(next); }
  useEffect(() => { if (previousRoute.current === routeKey) return; previousRoute.current = routeKey; routeClosing.current = open; setInternalOpen(false); changeRef.current?.(false); main.current?.focus({ preventScroll: true }); }, [routeKey, open]);
  return <RDialog.Root open={open} onOpenChange={changeOpen}><div ref={ref} {...props} className={cx('ui-app-shell', className)}><a className="ui-skip" href={`#${mainId}`}>{skipLinkLabel}</a>{topBar}<div className="ui-app-body"><aside className="ui-app-nav" aria-label={navLabel}>{nav}</aside><main ref={main} id={mainId} tabIndex={-1} className="ui-app-main">{children}</main></div></div><RDialog.Portal><RDialog.Overlay className="ui-overlay ui-nav-overlay" /><RDialog.Content className="ui-nav-drawer" aria-describedby={undefined} onCloseAutoFocus={event => { if (routeClosing.current) { event.preventDefault(); routeClosing.current = false; main.current?.focus({ preventScroll: true }); } }}><RDialog.Title className="ui-sr-only">{navLabel}</RDialog.Title><RDialog.Close className="ui-nav-close" aria-label={navCloseLabel}><X size={18} aria-hidden="true" /></RDialog.Close>{nav}</RDialog.Content></RDialog.Portal></RDialog.Root>;
});
export const AppShellNavTrigger = RDialog.Trigger;
export interface NavItem { readonly id: string; readonly label: string; readonly href: string; readonly icon?: ReactNode; readonly active?: boolean; readonly section?: string; }
interface NavListProps extends Props<'nav'> { items: readonly NavItem[]; renderLink: (item: NavItem, props: { className: string; 'aria-current': 'page' | undefined; children: ReactNode }) => ReactNode; }
export const NavList = forwardRef<HTMLElement, NavListProps>(function NavList({ items, renderLink, className, ...props }, ref) { return <nav ref={ref} {...props} className={cx('ui-nav-list', className)}>{items.map((item, index) => <div key={item.id}>{item.section && item.section !== items[index - 1]?.section ? <p className="ui-nav-section">{item.section}</p> : null}{renderLink(item, { className: cx('ui-nav-link', item.active && 'is-active'), 'aria-current': item.active ? 'page' : undefined, children: <>{item.icon}<span>{item.label}</span></> })}</div>)}</nav>; });
export const TopBar = forwardRef<HTMLElement, Omit<Props<'header'>, 'title'> & { eyebrow?: ReactNode; title?: ReactNode; actions?: ReactNode; menuButton?: ReactNode }>(function TopBar({ eyebrow, title, actions, menuButton, className, ...props }, ref) { return <header ref={ref} {...props} className={cx('ui-topbar', className)}><div className="ui-topbar-menu">{menuButton}</div><div className="ui-topbar-title">{eyebrow ? <span>{eyebrow}</span> : null}{title}</div><div className="ui-topbar-actions">{actions}</div></header>; });
